set_front_page.settings:
  type: config_object
  label: 'Set front page settings'
  mapping:
    site_frontpage_default:
      type: string
      label: "Default front page"
    types:
      type: sequence
      label: "Types of content allowed to be used"
      sequence:
        type: boolean
        label: 'Type'
